# Generated by Django 2.2.4 on 2022-02-22 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
