# Generated by Django 2.2.4 on 2022-02-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_registration_app', '0002_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='/static/imgs/user.png', upload_to='images/'),
        ),
    ]
